[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "https://docx-to-html.netlify.com/*"
to = "https://docx-to-html.troyv.dev/:splat"
status = 301
force = true

[build.processing]
skip_processing = true

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1"
